import Head from 'next/head'

export default function Home() {
  return (
    <div className='w-full flex justify-center items-center h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className=' text-red-300 bg-blue-400 w-[400px] text-[30px]'>Salom</h1>


    </div>
  )
}
